version: '3.'

services:
  frontend:
    image: bn-translator-frontend
    build:
      context: ./bangla-translator-frontend
      dockerfile: Dockerfile
    ports:
      - "81:81"  # Map Nginx port 80 to host 3000
    networks:
      - app-network


  backend:
    image: bn-translator-backend
    build:
      context: ./open-ai-api-mt
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    volumes:
      - ./open-ai-api-mt:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - app-network
  
  db:
    image: mysql:latest
    container_name: bn-translator-db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge





